#!/bin/bash
#
# check for readme
tmp_file="testing_readme"
# create a pseudo random file
ls $LSDIR > $tmp_file
cat $tmp_file | grep -q "man_1_simple_shell"
ret=$?

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result

if [[ $ret -eq 0 ]]; then
	   print_ok
	   i=`expr $i + 1`
	   total=`expr $total + 1`
else
	   print_ko
	   j=`expr $j + 1`
	   total=`expr $total + 1`
	   if [[ $SHOWERRORS -eq 1 ]]; then
	   	echo ""
	   	echo -e "[\033[31m************************\033[37m]"
	   	echo ">> Real output << "
	   	cat $tmp_file
	   	echo ">>**************<<"
	   	echo ""
	   	echo "> Expected output: "
	   	echo "definitely lost: 0 bytes in 0 blocks"
	   	echo ">>**************<<"
	    echo -e "[\033[31m************************\033[37m]"
	   fi
fi

# clean up
stop_shell
rm -f $tmp_file
